# Generated by Django 5.2.10 on 2026-01-30 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("startups", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FollowedStartup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "startup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to="startups.startup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following_startups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "followed_startups",
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="followed_st_user_id_9d8969_idx",
                    ),
                    models.Index(
                        fields=["startup"], name="followed_st_startup_6cf6a2_idx"
                    ),
                ],
                "unique_together": {("user", "startup")},
            },
        ),
        migrations.CreateModel(
            name="SavedStartup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "startup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by",
                        to="startups.startup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_startups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "saved_startups",
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="saved_start_user_id_f161b4_idx",
                    ),
                    models.Index(
                        fields=["startup"], name="saved_start_startup_ff7663_idx"
                    ),
                ],
                "unique_together": {("user", "startup")},
            },
        ),
    ]
