# Generated by Django 5.2.10 on 2026-01-30 11:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0002_initial"),
        ("startups", "0003_followedstartup_savedstartup"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="opportunity",
            index=models.Index(
                fields=["created_by", "-created_at"],
                name="opportuniti_created_d4611f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="opportunity",
            index=models.Index(
                fields=["startup", "status"], name="opportuniti_startup_d0c455_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="opportunity",
            index=models.Index(
                fields=["type", "status"], name="opportuniti_type_dfc37f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="opportunity",
            index=models.Index(
                fields=["-created_at"], name="opportuniti_created_02240e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="savedopportunity",
            index=models.Index(
                fields=["user", "-saved_at"], name="saved_oppor_user_id_5460ef_idx"
            ),
        ),
    ]
